//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configure
    {
        public int ConfigID { get; set; }
        public string Logo { get; set; }
        public string Favicon { get; set; }
        public string NameCompany { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string EmailReceive { get; set; }
        public string Phone { get; set; }
        public string Hotline { get; set; }
        public string Map { get; set; }
        public string FanpageFacebook { get; set; }
        public string IconFacebook { get; set; }
        public string IconTwiiter { get; set; }
        public string IconInstagram { get; set; }
        public string IconYoutube { get; set; }
        public string IconGoogle { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
    }
}
