//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuNavigation
    {
        public int MenuID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string MenuName { get; set; }
        public string IconMenu { get; set; }
        public int MenuParents { get; set; }
        public int PageStyle { get; set; }
        public Nullable<int> FormatPage { get; set; }
        public Nullable<int> GroupLink { get; set; }
        public string PageContent { get; set; }
        public string PageLink { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public bool Status { get; set; }
    }
}
