//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int SliderID { get; set; }
        public int SortID { get; set; }
        public string SliderName { get; set; }
        public string Description { get; set; }
        public string Images { get; set; }
        public string URL { get; set; }
        public bool Status { get; set; }
    }
}
